"""Self-Guardian schemas for agent observation, deviation detection, and reporting.

Defines the data models used by the Self-Guardian monitoring subsystem
to observe agent behavior, detect deviations, and generate reports.
"""
from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field


class DeviationType(str, Enum):
    """Types of deviations the Self-Guardian can detect."""
    UNAUTHORIZED_TOOL = "unauthorized_tool"
    DATA_CLASSIFICATION_MISMATCH = "data_classification_mismatch"
    EXTERNAL_FACING_VIOLATION = "external_facing_violation"
    STATE_CORRUPTION = "state_corruption"
    CONFIDENCE_DROP = "confidence_drop"
    RATE_LIMIT_EXCEEDED = "rate_limit_exceeded"


class AgentObservation(BaseModel):
    """A single observation of an agent action.

    Attributes:
        agent_name: Name of the agent that performed the action.
        action: Description of the action taken.
        tool_id: Identifier of the tool used, if any.
        target_entity: The entity the action was performed on.
        timestamp: When the observation was recorded.
        trace_id: Unique identifier for this trace/request.
        duration_ms: How long the action took in milliseconds.
        success: Whether the action completed successfully.
        error_message: Error details if the action failed.
    """
    agent_name: str
    action: str
    tool_id: str | None = None
    target_entity: str
    timestamp: datetime
    trace_id: str
    duration_ms: int
    success: bool
    error_message: str | None = None


class SelfGuardianAlert(BaseModel):
    """An alert generated by the Self-Guardian detector.

    Attributes:
        observation: The observation that triggered the alert.
        deviation: The type of deviation detected.
        severity: How severe the deviation is.
        description: Human-readable explanation of the alert.
        suggested_action: Recommended remediation action.
    """
    observation: AgentObservation
    deviation: DeviationType
    severity: Literal["info", "warning", "critical"]
    description: str
    suggested_action: str


class SelfGuardianReport(BaseModel):
    """Aggregated report of observations and deviations over a time window.

    Attributes:
        window_start: Start of the reporting window.
        window_end: End of the reporting window.
        total_observations: Total number of observations in the window.
        deviations: List of alerts generated from observations.
        agent_summaries: Per-agent summary with total, deviation count,
            and average duration, keyed by agent name.
    """
    window_start: datetime
    window_end: datetime
    total_observations: int
    deviations: list[SelfGuardianAlert] = Field(default_factory=list)
    agent_summaries: dict[str, dict] = Field(default_factory=dict)
