"""OntologyAI V5.1 — SOP schema (PRD §15.3).

Strict Pydantic v2 model for a Standard Operating Procedure generated by
WorkflowBuilder. Every field from PRD §15.3 is represented, including the
nested ``SOPStep`` shape. ``extra="forbid"`` + ``strict=True``.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict


class SOPStep(BaseModel):
    """A single step within an SOP (PRD §15.3 step shape)."""

    model_config = ConfigDict(extra="forbid", strict=True)

    step_number: int
    actor: str
    instruction: str
    input: str
    output: str
    approval_required: bool = False
    fallback_if_failed: str = ""


class SOP(BaseModel):
    """A Standard Operating Procedure generated by WorkflowBuilder (PRD §15.3)."""

    model_config = ConfigDict(extra="forbid", strict=True)

    sop_id: str
    title: str
    business_goal: str
    trigger: str
    preconditions: list[str] = []
    required_inputs: list[str] = []
    steps: list[SOPStep] = []
    decision_points: list[str] = []
    approval_points: list[str] = []
    exception_paths: list[str] = []
    completion_criteria: str
    owner_role: str
    reporting_output: str
    linked_objects: list[str] = []
    linked_actions: list[str] = []
