"""OntologyAI V5.1 — WorkflowSpec schema (PRD §15.2).

Strict Pydantic v2 model for a generated workflow specification. Every field
from PRD §15.2 is represented. ``extra="forbid"`` + ``strict=True`` so unknown
fields are rejected and type coercion is disabled.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, ConfigDict


class WorkflowSpec(BaseModel):
    """A reusable workflow specification generated by WorkflowBuilder (PRD §15.2)."""

    model_config = ConfigDict(extra="forbid", strict=True)

    workflow_spec_id: str
    workflow_name: str
    business_goal: str
    trigger: str
    preconditions: list[str] = []
    required_inputs: list[str] = []
    responsible_role: str
    decision_points: list[str] = []
    approval_points: list[str] = []
    exception_paths: list[str] = []
    expected_output: str
    success_metric: str
    linked_objects: list[str] = []
    sop_id: Optional[str] = None
    draft_runtime_targets: list[Literal["n8n", "custom_agent"]] = []
