-- Migration 007: Self-Guardian tables for agent observation and alert persistence
-- Enables Go HTMX dashboard to display Self-Guardian state from PostgreSQL.

CREATE TABLE IF NOT EXISTS self_guardian_observations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'default',
    agent_name VARCHAR(100) NOT NULL,
    action VARCHAR(200) NOT NULL,
    tool_id VARCHAR(100),
    target_entity VARCHAR(200),
    trace_id VARCHAR(100),
    duration_ms INTEGER DEFAULT 0,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sgo_tenant_created ON self_guardian_observations(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sgo_agent_created ON self_guardian_observations(agent_name, created_at DESC);
CREATE INDEX IF NOT EXISTS sgo_success ON self_guardian_observations(success) WHERE NOT success;

CREATE TABLE IF NOT EXISTS self_guardian_alerts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id VARCHAR(100) NOT NULL DEFAULT 'default',
    agent_name VARCHAR(100) NOT NULL,
    deviation_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL DEFAULT 'info',
    description TEXT,
    suggested_action TEXT,
    observation_action VARCHAR(200),
    observation_tool_id VARCHAR(100),
    observation_success BOOLEAN,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sga_tenant_created ON self_guardian_alerts(tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS sga_agent ON self_guardian_alerts(agent_name);
CREATE INDEX IF NOT EXISTS sga_severity ON self_guardian_alerts(severity) WHERE severity IN ('critical', 'warning');

COMMENT ON TABLE self_guardian_observations IS 'Agent action observations collected by the Self-Guardian subsystem';
COMMENT ON TABLE self_guardian_alerts IS 'Deviation alerts generated by Self-Guardian detector analysis';
